module.exports = {
  content: ['./src/resources/views/**/*.{hbs,handlebars,html,js}'],
  theme: {
    extend: {},
  },
  plugins: [],
  safelist: [
    'w-[90%]',
    'w-[80%]',
    'w-[70%]',
    'w-[60%]',
    'w-[50%]',
    'w-[40%]',
    'w-[30%]',
    'w-[20%]',
    'w-[10%]',
    'w-[95%]',
    'w-[85%]',
    'w-[75%]',
    'w-[65%]',
    'w-[55%]',
    'w-[45%]',
    'w-[35%]',
    'w-[25%]',
    'w-[15%]',
    'w-[5%]',
  ],
}
